void	good()
{
  puts("Line 1");
  puts("Line 2");
  puts("Line 3");
  puts("Line 4");
  puts("Line 5");
  puts("Line 6");
  puts("Line 7");
  puts("Line 8");
  puts("Line 9");
  puts("Line 10");
  puts("Line 11");
  puts("Line 12");
  puts("Line 13");
  puts("Line 14");
  puts("Line 15");
  puts("Line 16");
  puts("Line 17");
  puts("Line 18");
  puts("Line 19");
  puts("Line 20");
  puts("Line 21");
  puts("Line 22");
  puts("Line 23");
  puts("Line 24");
  puts("Line 25");
}

void	bad()
{
  puts("Line 1");
  puts("Line 2");
  puts("Line 3");
  puts("Line 4");
  puts("Line 5");
  puts("Line 6");
  puts("Line 7");
  puts("Line 8");
  puts("Line 9");
  puts("Line 10");
  puts("Line 11");
  puts("Line 12");
  puts("Line 13");
  puts("Line 14");
  puts("Line 15");
  puts("Line 16");
  puts("Line 17");
  puts("Line 18");
  puts("Line 19");
  puts("Line 20");
  puts("Line 21");
  puts("Line 22");
  puts("Line 23");
  puts("Line 24");
  puts("Line 25");
  puts("Error 1");
  puts("Error 2");
  puts("Error 3");
  puts("Error 4");
  puts("Error 5");
}
